knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            redirect_route: google_connect_check
